<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE siop_document [
<!ELEMENT siop_document (temperatures, levels, components, scenarios?)>
<!ELEMENT temperatures (temp+)>
<!ELEMENT temp EMPTY>
<!ATTLIST temp
          type (AP|BAT|USB|CHG|PA|WIFI) #REQUIRED
          default CDATA "1"
          min CDATA "1"
          max CDATA "1"
          step CDATA "1"
          init CDATA "5"
          hold CDATA "1"
          gap CDATA "0">
<!ELEMENT levels (level+)>
<!ELEMENT level EMPTY>
<!ATTLIST level
          id CDATA #REQUIRED
          temp CDATA #REQUIRED>
<!ELEMENT components (component+)>
<!ELEMENT component (limiter+)>
<!ATTLIST component
          name CDATA #REQUIRED
          tempType CDATA #REQUIRED>
<!ELEMENT scenarios (scenario*, scenario_group*)>
<!ELEMENT scenario (limiter+)>
<!-- you can use below delimiter on scenario name -->
<!-- "!" : intent, ":" : package, "," : plural    -->
<!ATTLIST scenario
          name CDATA #REQUIRED
          tempType CDATA #REQUIRED
          priority CDATA "0">
<!ELEMENT scenario_group (scenario+)>
<!ELEMENT scenario EMPTY>
<!ATTLIST scenario
          name CDATA #REQUIRED
          limiter CDATA #REQUIRED
          step CDATA "-1"
          delay CDATA "0"
          cond (sensor_check|for_request|for_temporary) #IMPLIED
          temp CDATA "370"
          gap CDATA "20"
          value CDATA #REQUIRED>
<!ELEMENT limiter EMPTY>
<!ATTLIST limiter
          name CDATA #REQUIRED
          step CDATA "-1"
          delay CDATA "0"
          cond (sensor_check|for_request|for_temporary) #IMPLIED
          temp CDATA "370"
          gap CDATA "20"
          value CDATA #REQUIRED>
]>

<siop_document>

    <overheatcontrol>
        <complex>
            <LTB    formula="SKIN*PA*AP"  temp="484.541.569" />
            <LCD    formula="SKIN*PA*AP"  temp="469.525.550" />
            <GDM    formula="SKIN*PA*AP"  temp="447.491.499" />
            <GDMLTB formula="SKIN*PA*AP"  temp="465.510.519" />
            <SS     formula="AP*BAT*PA"   temp="663.457.593" />
        </complex>
    </overheatcontrol>

    <modelsettings>
        <Skin type="LRP2"/>
        <sensors>
            <LTB_SENSOR type="PALM" />
        </sensors>
    </modelsettings>

    <components>

        <component name="AP" tempType="SKIN" >
            <limiter name="CPUFreqMax" step="0" temp="360:380:450:470" value="-1:1766400:1766400:1324800" />
            <limiter name="GPUFreqMax" step="0" temp="360:380:450:470" value="-1:450:450:315" />
            <limiter name="DexOptCpuset"        temp="360"             value="-1:1"   />
        </component>

        <component name="DISPLAY" tempType="SKIN">
            <limiter name="Brightness" temp="390" value="-1:204:149" />
            <limiter name="MultiWindow" temp="450:470:500" value="-1:1:1" delay="0:300:0" />
        </component>

        <component name="CP" tempType="SKIN">
            <limiter name="DLThrot" temp="410:430" value="-1:2" />
            <limiter name="CpLowMode" temp="340:360" value="-1:2" />
            <limiter name="SADisable" temp="420" value="-1:1" />
        </component>

        <component name="CHG+DISPLAY" tempType="SKIN">
            <limiter name="Charging" temp="350" value="-1:70" />
        </component>

    </components>

    <scenarios>

        <scenario name="ScreenOffInCall" tempType="SKIN" priority="1" >
            <limiter name="Charging" value="70" />
        </scenario>

        <scenario name="ScreenOff" tempType="SKIN" priority="1" >
            <limiter name="DexOptCpuset" temp="340:350" value="-1:1" />
        </scenario>

        <scenario name="SIPStart" tempType="SKIN" priority="1" >
            <limiter name="CPUFreqMax" cond="for_temporary" temp="450" value="-1:1766400" />
            <limiter name="GPUFreqMax" cond="for_temporary" temp="450" value="-1:450"     />
        </scenario>

        <scenario name="AppStart" tempType="SKIN" priority="1" >
            <limiter name="CPUFreqMax" cond="for_temporary" temp="450" value="-1:1766400" />
            <limiter name="GPUFreqMax" cond="for_temporary" temp="450" value="-1:450"     />
        </scenario>

        <scenario name="Badge" tempType="SKIN" priority="1" >
            <limiter name="CPUFreqMax" cond="for_temporary" temp="450" value="-1:1766400" />
            <limiter name="GPUFreqMax" cond="for_temporary" temp="450" value="-1:450"     />
        </scenario>

        <scenario name="CallStart" tempType="SKIN" priority="1" >
            <limiter name="CPUFreqMax" cond="for_temporary" temp="450" value="-1:1766400" />
            <limiter name="GPUFreqMax" cond="for_temporary" temp="450" value="-1:450"     />
        </scenario>

        <scenario name="WakeUp" tempType="SKIN" priority="1" >
            <limiter name="CPUFreqMax" cond="for_temporary" temp="450" value="-1:1766400" />
            <limiter name="GPUFreqMax" cond="for_temporary" temp="450" value="-1:450"     />
        </scenario>

        <scenario name="VtCallControl" tempType="SKIN" priority="1">
            <limiter name="Brightness"       temp="320:340:410:430" value="-1:204:204:149" />
            <limiter name="CPUFreqLittleMax" temp="300" value="-1:1651200" />
            <limiter name="CPUFreqMax"       temp="300" value="-1:1516800" />
            <limiter name="CameraFps"        temp="340" value="-1:1" />
            <limiter name="Charging"         temp="320" value="-1:20" />
            <limiter name="GPUFreqMax"       temp="300" value="-1:315" />
        </scenario>

        <scenario name="CameraRecording!Camera_recording,Camera_recordingDual" tempType="SKIN">
            <limiter name="Brightness" temp="330:350:390:410:430" value="-1:255:255:204:149" />
        </scenario>

        <scenario name="ARGroup:com.sec.android.mimage.avatarstickers,com.samsung.android.aremojieditor,com.samsung.android.ardrawing" tempType="SKIN" >
            <limiter name="GPUFreqMax" temp="360:380" value="-1:315" />
        </scenario>

        <scenario name="Navigation" tempType="SKIN" >
            <limiter name="Brightness" temp="410:430" value="174:149" />
        </scenario>

        <scenario name="SmartSwitchTransfer" tempType="SKIN" priority="2" >
            <limiter name="CPUFreqMax"       tempType="SKIN" temp="360" p="50" i="1" d="30" unit="1000" min="1056000"/>
            <limiter name="CPUFreqLittleMax" temp="330:340:360:370"         value="-1:1651200:1516800:1324800"       />
            <limiter name="OverLimit"        temp="400"                     value="1516800:-1"                      />
            <limiter name="Charging"         temp="300:320:350:370"         value="-1:70:70:0"                      />
            <limiter name="WifiP2pTput"      temp="310:330:340:360:400:450" value="-1:400:300:200:100:50"           />
            <limiter name="JobRestriction"   temp="340"                     value="1" />
        </scenario>

        <scenario name="SmartSwitchAppInstall" tempType="SKIN" priority="1" >
            <limiter name="CPUFreqMax"         tempType="SKIN" temp="360" p="50" i="1" d="30" unit="1000" min="1056000"/>
            <limiter name="CPUFreqLittleMax"   temp="330:340:360:370"         value="-1:1651200:1516800:1324800"       />
            <limiter name="Charging"           temp="300:320:350:370"         value="-1:70:70:0"                      />
            <limiter name="JobRestriction"     temp="340"                     value="1" />
        </scenario>	

        <scenario name="HighBrightness"  tempType="SKIN*BAT" priority="1" region="XSG" >
             <limiter name="DLThrot"   temp="440.370:450.380:470.400" value="-1:2:2" delay="0:1800:0" />
             <limiter name="SADisable" temp="450.380:460.390:480.400" value="-1:1:1" delay="0:1800:0" />
        </scenario>

        <scenario name="HighBrightness"  tempType="SKIN*BAT" priority="1" region="KSA" >
             <limiter name="DLThrot"   temp="440.370:450.380:470.400" value="-1:2:2" delay="0:1800:0" />
             <limiter name="SADisable" temp="450.380:460.390:480.400" value="-1:1:1" delay="0:1800:0" />
        </scenario>

        <scenario name="Heavyuser" tempType="SKIN" priority="1" >
            <limiter name="CPUFreqMax" cond="for_temporary" tempType="SKIN" temp="430" p="50" i="1" d="30" unit="1000" min="1766400"/>
            <limiter name="GPUFreqMax" cond="for_temporary" tempType="SKIN" temp="430" p="50" i="1" d="30" unit="0.4" min="450" />
        </scenario>

        <scenario_group name="GameThermalCpuControl" tempType="SKIN" >
            <scenario id="-4"  limiter="CPUFreqMax"                             value="1056000" />
            <scenario id="-3"  limiter="CPUFreqMax" step="0" temp="360:370:390" value="-1:1766400:1056000" />
            <scenario id="-2"  limiter="CPUFreqMax" step="0" temp="360:370:390" value="-1:1766400:1324800" />
            <scenario id="-1"  limiter="CPUFreqMax" step="0" temp="360:370:390" value="-1:1766400:1516800" />
            <scenario id="0"   limiter="CPUFreqMax" step="0" temp="360:370:390" value="-1:1862400:1766400" />
            <scenario id="1"   limiter="CPUFreqMax" step="0" temp="360:370:390" value="-1:2035200:1862400" />
            <scenario id="2"   limiter="CPUFreqMax" step="0" temp="360:370:390" value="-1:2208000:2035200" />
            <scenario id="3"   limiter="CPUFreqMax" step="0" temp="360:370:390" value="-1:2380800:2208000" />
            <scenario id="4"   limiter="CPUFreqMax"                             value="-1"                 />
        </scenario_group>

        <scenario_group name="GameThermalGpuControl" tempType="SKIN" >
            <scenario id="-3" limiter="GPUFreqMax"                              value="315" />
            <scenario id="-2" limiter="GPUFreqMax" step="0" temp="360:370:390"  value="-1:315:315" />
            <scenario id="-1" limiter="GPUFreqMax" step="0" temp="360:370:390"  value="-1:450:315" />
            <scenario id="0"  limiter="GPUFreqMax" step="0" temp="360:370:390"  value="-1:550:450" />
            <scenario id="1"  limiter="GPUFreqMax"                              value="-1" />
        </scenario_group>

    </scenarios>

</siop_document>
