<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE siop_document [
<!ELEMENT siop_document (temperatures, levels, components, scenarios?)>
<!ELEMENT temperatures (temp+)>
<!ELEMENT temp EMPTY>
<!ATTLIST temp
          type (AP|BAT|USB|CHG|PA|WIFI) #REQUIRED
          default CDATA "1"
          min CDATA "1"
          max CDATA "1"
          step CDATA "1"
          init CDATA "5"
          hold CDATA "1"
          gap CDATA "0">
<!ELEMENT levels (level+)>
<!ELEMENT level EMPTY>
<!ATTLIST level
          id CDATA #REQUIRED
          temp CDATA #REQUIRED>
<!ELEMENT components (component+)>
<!ELEMENT component (limiter+)>
<!ATTLIST component
          name CDATA #REQUIRED
          tempType CDATA #REQUIRED>
<!ELEMENT scenarios (scenario*, scenario_group*)>
<!ELEMENT scenario (limiter+)>
<!-- you can use below delimiter on scenario name -->
<!-- "!" : intent, ":" : package, "," : plural    -->
<!ATTLIST scenario
          name CDATA #REQUIRED
          tempType CDATA #REQUIRED
          priority CDATA "0">
<!ELEMENT scenario_group (scenario+)>
<!ELEMENT scenario EMPTY>
<!ATTLIST scenario
          name CDATA #REQUIRED
          limiter CDATA #REQUIRED
          step CDATA "-1"
          delay CDATA "0"
          cond (sensor_check|for_request|for_temporary) #IMPLIED
          temp CDATA "370"
          gap CDATA "20"
          value CDATA #REQUIRED>
<!ELEMENT limiter EMPTY>
<!ATTLIST limiter
          name CDATA #REQUIRED
          step CDATA "-1"
          delay CDATA "0"
          cond (sensor_check|for_request|for_temporary) #IMPLIED
          temp CDATA "370"
          gap CDATA "20"
          value CDATA #REQUIRED>
]>

<siop_document>

    <overheatcontrol>
        <complex>
            <DEX formula="SKIN" temp="470" />
        </complex>
    </overheatcontrol>
    <modelsettings>
        <temperatures>
            <temp type="AP"   default="15" min="15" max="15" step="0" gap="100" />
            <temp type="BAT"  default="1"  min="1"  max="1"  step="0" gap="0" />
            <temp type="USB"  default="1"  min="1"  max="1"  step="0" gap="0" />
            <temp type="CHG"  default="1"  min="1"  max="1"  step="0" gap="0" />
            <temp type="PA"   default="1"  min="1"  max="1"  step="0" gap="0" />
            <temp type="WIFI" default="1"  min="1"  max="1"  step="0" gap="0" />
        </temperatures>
        <levels tempType="SKIN" >
            <level id="-3" temp="300" />
            <level id="-2" temp="320" />
            <level id="-1" temp="340" />
            <level id="0"  temp="360" />
            <level id="1"  temp="380" />
            <level id="2"  temp="400" />
            <level id="3"  temp="420" />
            <level id="4"  temp="440" />
            <level id="5"  temp="460" />
            <level id="6"  temp="480" />
            <level id="7"  temp="500" />
            <level id="8"  temp="520" />
        </levels>
    </modelsettings>

    <components>

        <component name="AP" tempType="SKIN" >
            <limiter name="CPUFreqMax" step="1" temp="380"             value="-1"                   />
            <limiter name="GPUFreqMax" step="1" temp="380"             value="-1"                   />
            <limiter name="AppInstallDelay"     temp="400:420"         value="-1:10000"             />
            <limiter name="DexOptCpuset"        temp="360"             value="-1:1"                 />
            <limiter name="BackgroundCpuset"    temp="360"             value="-1:100:200:300"       />
            <limiter name="TABoost"             temp="400"             value="-1:1"                 />
        </component>

        <component name="CAM" tempType="SKIN" >
            <limiter name="CameraAr"            temp="400:420:450:480"             value="-1:1:2:3"       />
            <limiter name="CameraOverheatLevel" temp="350:370:390:410:430:450:460" value="-1:1:2:3:4:5:6" />
            <limiter name="DualRecording"       temp="350"                         value="-1:1"           />
        </component>

        <component name="CHG" tempType="SKIN">
            <limiter name="Charging" temp="380" value="-1" />
        </component>

        <component name="CP" tempType="SKIN">
            <limiter name="CpLowMode" value="-1" />
        </component>

        <component name="DISPLAY" tempType="SKIN">
            <limiter name="Brightness"     temp="380"         value="-1"                     />
            <limiter name="LimitHrr"       temp="530"         value="-1:1"                   />
            <limiter name="AppCastDisable" temp="450:470:500" value="-1:1:1" delay="0:300:0" />
            <limiter name="MultiWindow"    temp="450:470:500" value="-1:1:1" delay="0:300:0" />
        </component>

        <component name="WIFI" tempType="SKIN">
            <limiter name="WifiTput"    tempType="SKIN" temp="450" p="50" i="2" d="50" unit="0.1" min="300" />
            <limiter name="WifiP2pTput" tempType="SKIN" temp="450" p="50" i="2" d="50" unit="0.1" min="300"/>
            <limiter name="WifiAwareTput" tempType="SKIN" temp="450" p="50" i="2" d="50" unit="0.1" min="300"/>
            <limiter name="HotspotTput" tempType="SKIN" temp="450" p="50" i="2" d="50" unit="0.1" min="300"/>
            <limiter name="SmartBonding"                temp="400" value="-1:1"                            />
        </component>

        <component name="CHG+DISPLAY" tempType="SKIN">
            <limiter name="Charging" temp="360" value="-1:80" />
        </component>

    </components>

    <scenarios>
        <scenario name="ScreenOff" tempType="SKIN" priority="1" >
            <limiter name="Charging" value="100" />
        </scenario>

        <scenario name="TPBoost:com.FTATS,com.fafa" tempType="SKIN" >
            <limiter name="CPUFreqMax" value="-1" />
        </scenario>

        <scenario name="SIPStart" tempType="SKIN" priority="1" >
            <limiter name="CPUFreqMax" cond="for_temporary" value="-1" />
            <limiter name="GPUFreqMax" cond="for_temporary" value="-1" />
        </scenario>

        <scenario name="AppStart" tempType="SKIN" priority="1" >
            <limiter name="CPUFreqMax" cond="for_temporary" value="-1" />
            <limiter name="GPUFreqMax" cond="for_temporary" value="-1" />
        </scenario>

        <scenario name="Badge" tempType="SKIN" priority="1" >
            <limiter name="CPUFreqMax" cond="for_temporary" value="-1" />
            <limiter name="GPUFreqMax" cond="for_temporary" value="-1" />
        </scenario>

        <scenario name="CallStart" tempType="SKIN" priority="1" >
            <limiter name="CPUFreqMax" cond="for_temporary" value="-1" />
            <limiter name="GPUFreqMax" cond="for_temporary" value="-1" />
        </scenario>

        <scenario name="WakeUp" tempType="SKIN" priority="1" >
            <limiter name="CPUFreqMax" cond="for_temporary" value="-1" />
            <limiter name="GPUFreqMax" cond="for_temporary" value="-1" />
        </scenario>

        <scenario name="MultiWindow" tempType="SKIN" priority="2" >
            <limiter name="LimitHrr"            temp="430"     value="-1:1" />
        </scenario>

        <scenario name="Navigation" tempType="SKIN" priority="1" >
            <limiter name="CameraFps"       temp="360:380:420:450" value="-1:24:24:15" />
        </scenario>

        <scenario name="Dex" tempType="SKIN" priority="2" >
            <limiter name="LimitHrr"        temp="430" value="-1:1" />
            <limiter name="DynamicFpsLevel" temp="430" value="-1:30"/>
        </scenario>

        <scenario name="LowTemp" tempType="BAT" priority="3" >
            <limiter name="CPUFreqMax" value="-1" />
            <limiter name="Charging"   value="-1" />
        </scenario>

        <scenario name="SmartSwitchTransfer" tempType="SKIN" priority="2" >
            <limiter name="Charging"                    temp="300"                     value="-1:70"       />
            <limiter name="JobRestriction"              temp="340"                     value="1"           />
            <limiter name="WifiTput"                    temp="380" p="50" i="2" d="50" unit="0.1" min="400"/>
            <limiter name="WifiP2pTput"                 temp="380" p="50" i="2" d="50" unit="0.1" min="400"/>
        </scenario>

        <scenario name="SmartSwitchAppInstall" tempType="SKIN" priority="1" >
            <limiter name="Charging"         temp="300"                      value="-1:70" />
            <limiter name="JobRestriction"   temp="340"                      value="1" />
        </scenario>

        <scenario name="retailmode:com.samsung.rms.retailagent.global" tempType="SKIN" priority="1">
            <limiter name="Charging" value="70" />
        </scenario>

        <scenario name="scrrensaver:com.samsung.android.retail.screensaver" tempType="SKIN" priority="1">
            <limiter name="Charging" value="70" />
        </scenario>

        <scenario name="SPA" tempType="SKIN" priority="3" >
            <limiter name="CPUFreqMax" cond="for_temporary" value="-1" />
            <limiter name="GPUFreqMax" cond="for_temporary" value="-1" />
            <limiter name="OverLimit"                       value="-1" />
        </scenario>

        <scenario name="GameSDK" tempType="SKIN" priority="1" >
            <limiter name="CPUFreqMax" cond="for_temporary" value="-1" />
            <limiter name="GPUFreqMax" cond="for_temporary" value="-1" />
            <limiter name="OverLimit"  value="-1" />
        </scenario>

        <scenario name="SpeedControlForTG" tempType="SKIN" priority="1" >
            <limiter name="OverLimit"          value="-1"/>
        </scenario>

        <scenario name="BrightnessControlForTG" tempType="SKIN" priority="1" >
            <limiter name="Brightness"  temp="340:360:380:400:420:450:470:530:550:600" value="-1:230:210:180:150:120:100:100:70:15" />
        </scenario>

        <scenario name="HrrControlForTG" tempType="SKIN" priority="1" >
            <limiter name="LimitHrr" temp="380" value="-1:1" />
        </scenario>

        <scenario name="LrrControlForTG" tempType="SKIN" priority="1" >
            <limiter name="LimitHrr" temp="380" value="1" />
        </scenario>

    </scenarios>

</siop_document>