<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE siop_document [
<!ELEMENT siop_document (temperatures, levels, components, scenarios?)>
<!ELEMENT temperatures (temp+)>
<!ELEMENT temp EMPTY>
<!ATTLIST temp
          type (AP|BAT|USB|CHG|PA|WIFI) #REQUIRED
          default CDATA "1"
          min CDATA "1"
          max CDATA "1"
          step CDATA "1"
          init CDATA "5"
          hold CDATA "1"
          gap CDATA "0">
<!ELEMENT levels (level+)>
<!ELEMENT level EMPTY>
<!ATTLIST level
          id CDATA #REQUIRED
          temp CDATA #REQUIRED>
<!ELEMENT components (component+)>
<!ELEMENT component (limiter+)>
<!ATTLIST component
          name CDATA #REQUIRED
          tempType CDATA #REQUIRED>
<!ELEMENT scenarios (scenario*, scenario_group*)>
<!ELEMENT scenario (limiter+)>
<!-- you can use below delimiter on scenario name -->
<!-- "!" : intent, ":" : package, "," : plural    -->
<!ATTLIST scenario
          name CDATA #REQUIRED
          tempType CDATA #REQUIRED
          priority CDATA "0">
<!ELEMENT scenario_group (scenario+)>
<!ELEMENT scenario EMPTY>
<!ATTLIST scenario
          name CDATA #REQUIRED
          limiter CDATA #REQUIRED
          step CDATA "-1"
          delay CDATA "0"
          cond (sensor_check|for_request|for_temporary) #IMPLIED
          temp CDATA "370"
          gap CDATA "20"
          value CDATA #REQUIRED>
<!ELEMENT limiter EMPTY>
<!ATTLIST limiter
          name CDATA #REQUIRED
          step CDATA "-1"
          delay CDATA "0"
          cond (sensor_check|for_request|for_temporary) #IMPLIED
          temp CDATA "370"
          gap CDATA "20"
          value CDATA #REQUIRED>
]>

<siop_document>

    <modelsettings>
        <temperatures>
            <temp type="AP"   default="15" min="15" max="15" step="0" gap="100" />
            <temp type="BAT"  default="1"  min="1"  max="1"  step="0" gap="0" />
            <temp type="USB"  default="1"  min="1"  max="1"  step="0" gap="0" />
            <temp type="CHG"  default="1"  min="1"  max="1"  step="0" gap="0" />
            <temp type="PA"   default="1"  min="8"  max="8"  step="0" gap="50" />
            <temp type="WIFI" default="15" min="15" max="15" step="0" gap="50" />
        </temperatures>
        <levels>
            <level id="-3" temp="310" />
            <level id="-2" temp="330" />
            <level id="-1" temp="350" />
            <level id="0"  temp="370" />
            <level id="1"  temp="390" />
            <level id="2"  temp="410" />
            <level id="3"  temp="430" />
            <level id="4"  temp="450" />
            <level id="5"  temp="470" />
            <level id="6"  temp="500" />
            <level id="7"  temp="550" />
        </levels>
    </modelsettings>

    <limiters> <!-- will be removed -->
        <!-- AP -->
        <limiter name="CPUFreqMax"       default="-1" /> 
        <limiter name="GPUFreqMax"       default="-1" />
        <limiter name="DynamicFpsLevel"  default="-1" />
        <limiter name="AppInstallDelay"  default="-1" />
        <limiter name="DexToOatAffinity" default="-1" />
        <!-- CHG -->
        <limiter name="Charging"         default="-1" />
        <!-- DISPLAY -->
        <limiter name="Brightness"       default="-1" />
        <!-- SPK -->
        <limiter name="MaxVolume"        default="-1" />
        <!-- WIFI -->
        <limiter name="WifiTput"         default="-1" />
        <limiter name="WifiP2pTput"      default="-1" />
        <limiter name="HotspotTput"      default="-1" />
        <limiter name="SmartBonding"     default="-1" />
        <!-- CAM -->
        <limiter name="CameraFlash"      default="-1" />
        <limiter name="Recording"        default="-1" />
        <limiter name="DualRecording"    default="-1" />
        <limiter name="RecordingLowFps"  default="-1" />
        <!-- Direct -->
        <limiter name="CameraStart"      default="-1" />
        <limiter name="LiveThumbnail"    default="-1" />
        <limiter name="MultiWindow"      default="-1" />
    </limiters>

    <components>

        <component name="AP" tempType="AP" >
            <limiter name="CPUFreqMax" step="1" temp="370" value="-1" />
            <limiter name="GPUFreqMax" step="1" temp="370" value="-1" />
            <limiter name="AppInstallDelay" value="-1" />
        </component>

        <component name="CAM" tempType="AP" >
            <limiter name="DualRecording" temp="370" value="-1" />
        </component>

        <component name="CHG" tempType="AP+CHG+BAT">
            <limiter name="Charging" temp="370" value="-1" />
        </component>

        <component name="DISPLAY" tempType="AP+BAT">
            <limiter name="Brightness" temp="370" gap="20" value="-1" />
        </component>

        <component name="WIFI" tempType="WIFI+BAT">
            <limiter name="WifiTput" temp="370" gap = "20" value="-1" />
            <limiter name="SmartBonding" temp="370" value="-1" />
        </component>

        <component name="AP+DISPLAY" tempType="AP" >
            <limiter name="AppInstallDelay" temp="370" gap="20" value="-1" />
        </component>
        
        <component name="CHG+DISPLAY" tempType="AP+CHG+BAT">
            <limiter name="Charging" temp="370" gap="20" value="-1" />
        </component>

    </components>

    <scenarios>
        <scenario name="SIPStart" tempType="AP" priority="1" >
            <limiter name="CPUFreqMax" cond="for_temporary" value="-1" />
            <limiter name="GPUFreqMax" cond="for_temporary" value="-1" />
        </scenario>

        <scenario name="AppStart" tempType="AP" priority="1" >
            <limiter name="CPUFreqMax" cond="for_temporary" value="-1" />
            <limiter name="GPUFreqMax" cond="for_temporary" value="-1" />
        </scenario>

        <scenario name="Badge" tempType="AP" priority="1" >
            <limiter name="CPUFreqMax" cond="for_temporary" value="-1" />
            <limiter name="GPUFreqMax" cond="for_temporary" value="-1" />
        </scenario>

        <scenario name="WakeUp" tempType="AP" priority="1" >
            <limiter name="CPUFreqMax" cond="for_temporary" value="-1" />
            <limiter name="GPUFreqMax" cond="for_temporary" value="-1" />
        </scenario>

        <scenario name="LowTemp" tempType="BAT" priority="3" >
            <limiter name="CPUFreqMax" value="-1" />
            <limiter name="Charging"   value="-1" />
        </scenario>

        <scenario name="SPA" tempType="SKIN" priority="1" >
            <limiter name="CPUFreqMax" cond="for_temporary" value="-1" />
            <limiter name="GPUFreqMax" cond="for_temporary" value="-1" />
            <limiter name="OverLimit"                       value="-1" />
        </scenario>

        <scenario name="GameSDK" tempType="SKIN" priority="1" >
            <limiter name="CPUFreqMax" cond="for_temporary" value="-1" />
            <limiter name="GPUFreqMax" cond="for_temporary" value="-1" />
            <limiter name="OverLimit"  value="-1" />
        </scenario>

    </scenarios>

</siop_document>